# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://manikishan.github.io
title: KillSwitch
email: manikishanghantasala@gmail.com
author: Mani Kishan
author-img: manikishan.jpg
description: > # "Write an awesome description for your new site here. 
  A simple blog whuch takes you to a world of amazing technical and non-technical news.
copyright: 'Copyright &copy; 2015 Manikishan. All Rights Reserved.'
credits: 'Credits: this is a opensource free site'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ManikishanG
  - title: github
    url: https://github.com/manikishan
  - title: wordpress
    url: https://manikishan.wordpress.com
